name: CI - Markdown Lint and Spell Check

# on:
#   pull_request:
#     branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm install

      - name: Markdownlint Permissions
        run: chmod +x node_modules/.bin/markdownlint

      - name: Husky Permissions
        run: chmod +x .husky/*

        # Adjust this as necessary to lint and spell check the correct files
      - name: Run Markdown Lint
        run: npx markdownlint "**/*.md"

        # Adjust this as necessary to lint and spell check the correct files
      - name: Run Spell Check
        run: npx cspell "**/*.md"
