name: CI - Markdown Lint and Spell Check

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Dependencies
        run: npm install

      - name: Run Markdown Lint
        run: npx markdownlint "**/*.md"

      - name: Run Spell Check
        run: npx cspell "**/*.md"
